services:
  - type: web
    name: xebia-api-gateway-mritunjai
    env: docker
    plan: free
    dockerContext: backend
    dockerfilePath: backend/api-gateway/Dockerfile
    envVars:
      - key: SERVER_PORT
        value: "8080"
      - key: JWT_SECRET
        generateValue: true
      - key: REDIS_HOST
        value: "YOUR_UPSTASH_REDIS_URL_HERE"
      - key: SERVICES_COURSE
        value: http://xebia-course-service-mritunjai:8084

  - type: web
    name: xebia-course-service-mritunjai
    env: docker
    plan: free
    dockerContext: backend
    dockerfilePath: backend/course-service/Dockerfile
    envVars:
      - key: SERVER_PORT
        value: "8084"
      - key: JWT_SECRET
        generateValue: true
      - key: DB_URL
        fromDatabase:
          name: xebia-postgres-mritunjai
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: xebia-postgres-mritunjai
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: xebia-postgres-mritunjai
          property: password
      - key: REDIS_HOST
        value: "YOUR_UPSTASH_REDIS_URL_HERE"

databases:
  - name: xebia-postgres-mritunjai
    databaseName: lms
    user: lms
    plan: free
