services:
  - type: web
    name: xebia-api-gateway-mritunjai
    env: java
    rootDir: backend
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar api-gateway/target/api-gateway-*.jar
    envVars:
      - key: SERVER_PORT
        value: "8080"
      - key: JWT_SECRET
        generateValue: true
      - key: REDIS_HOST
        fromService:
          type: pserv
          name: xebia-redis-mritunjai
          property: host
      - key: SERVICES_COURSE
        value: http://xebia-course-service-mritunjai:8084

  - type: web
    name: xebia-course-service-mritunjai
    env: java
    rootDir: backend
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar course-service/target/course-service-*.jar
    envVars:
      - key: SERVER_PORT
        value: "8084"
      - key: JWT_SECRET
        generateValue: true
      - key: DB_URL
        fromDatabase:
          name: xebia-postgres-mritunjai
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: xebia-postgres-mritunjai
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: xebia-postgres-mritunjai
          property: password
      - key: REDIS_HOST
        fromService:
          type: pserv
          name: xebia-redis-mritunjai
          property: host

  - type: pserv
    name: xebia-redis-mritunjai
    env: docker
    repo: https://github.com/render-examples/redis.git

databases:
  - name: xebia-postgres-mritunjai
    databaseName: lms
    user: lms
