server.port: ${SERVER_PORT:8084}
spring:
  application.name: course-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lms}
    username: ${DB_USERNAME:lms}
    password: ${DB_PASSWORD:lms}
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate.default_schema: course
  flyway:
    schemas: course
    default-schema: course
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
management.endpoints.web.exposure.include: health,info,metrics
