server.port: ${SERVER_PORT:8088}
spring:
  application.name: assessment-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lms}
    username: ${DB_USERNAME:lms}
    password: ${DB_PASSWORD:lms}
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate.default_schema: assessment
  flyway:
    schemas: assessment
    default-schema: assessment
management.endpoints.web.exposure.include: health,info,metrics
