server:
  port: ${SERVER_PORT:8082}
spring:
  application:
    name: organisation-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lms}
    username: ${DB_USERNAME:lms}
    password: ${DB_PASSWORD:lms}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: organisation
  flyway:
    schemas: organisation
    default-schema: organisation
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
