/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainerIndexRouteImport } from './routes/trainer/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TrainerSettingsRouteImport } from './routes/trainer/settings'
import { Route as TrainerReportsRouteImport } from './routes/trainer/reports'
import { Route as TrainerLeaderboardRouteImport } from './routes/trainer/leaderboard'
import { Route as TrainerEventsRouteImport } from './routes/trainer/events'
import { Route as TrainerEvaluationRouteImport } from './routes/trainer/evaluation'
import { Route as TrainerAssessmentBuilderRouteImport } from './routes/trainer/assessment-builder'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as StudentNotificationsRouteImport } from './routes/student/notifications'
import { Route as StudentFeedbackRouteImport } from './routes/student/feedback'
import { Route as StudentEventsRouteImport } from './routes/student/events'
import { Route as StudentCoursesRouteImport } from './routes/student/courses'
import { Route as StudentBatchesRouteImport } from './routes/student/batches'
import { Route as StudentAssessmentsRouteImport } from './routes/student/assessments'
import { Route as AdminTrainerRouteImport } from './routes/admin/trainer'
import { Route as AdminOrganiserRouteImport } from './routes/admin/organiser'
import { Route as AdminCurriculumRouteImport } from './routes/admin/curriculum'
import { Route as AdminBatchesRouteImport } from './routes/admin/batches'
import { Route as AdminAssessmentsRouteImport } from './routes/admin/assessments'
import { Route as TrainerBatchesIndexRouteImport } from './routes/trainer/batches/index'
import { Route as StudentResultsIndexRouteImport } from './routes/student/results/index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as AdminCurriculumIndexRouteImport } from './routes/admin/curriculum/index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AdminBatchesIndexRouteImport } from './routes/admin/batches/index'
import { Route as AdminAssessmentsIndexRouteImport } from './routes/admin/assessments/index'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/admin/analytics/index'
import { Route as TrainerBatchesIdRouteImport } from './routes/trainer/batches/$id'
import { Route as StudentTakeSlugRouteImport } from './routes/student/take/$slug'
import { Route as StudentTakeCodingSlugRouteImport } from './routes/student/take-coding/$slug'
import { Route as StudentCourseCourseIdRouteImport } from './routes/student/course/$courseId'
import { Route as StudentCertificateSubmissionIdRouteImport } from './routes/student/certificate/$submissionId'
import { Route as StudentAssessmentAssessmentIdRouteImport } from './routes/student/assessment/$assessmentId'
import { Route as AdminCurriculumCourseIdRouteImport } from './routes/admin/curriculum/$courseId'
import { Route as AdminCoursesBuilderRouteImport } from './routes/admin/courses/builder'
import { Route as AdminCoursesCourseSlugRouteImport } from './routes/admin/courses/$courseSlug'
import { Route as AdminCategoriesCategorySlugRouteImport } from './routes/admin/categories/$categorySlug'
import { Route as AdminBatchesTrainersRouteImport } from './routes/admin/batches/trainers'
import { Route as AdminBatchesAnalyticsRouteImport } from './routes/admin/batches/analytics'
import { Route as AdminBatchesAllocationsRouteImport } from './routes/admin/batches/allocations'
import { Route as AdminBatchesAllocateRouteImport } from './routes/admin/batches/allocate'
import { Route as AdminBatchesBatchIdRouteImport } from './routes/admin/batches/$batchId'
import { Route as AdminAssessmentsAnalyticsRouteImport } from './routes/admin/assessments/analytics'
import { Route as AdminAssessmentsAssessmentIdRouteImport } from './routes/admin/assessments/$assessmentId'
import { Route as AdminAnalyticsTrendsRouteImport } from './routes/admin/analytics/trends'
import { Route as AdminAnalyticsSkillGapRouteImport } from './routes/admin/analytics/skill-gap'
import { Route as AdminAnalyticsRecommendationsRouteImport } from './routes/admin/analytics/recommendations'
import { Route as AdminAnalyticsProgramsRouteImport } from './routes/admin/analytics/programs'
import { Route as AdminAnalyticsPredictiveRouteImport } from './routes/admin/analytics/predictive'
import { Route as AdminAnalyticsPillarsRouteImport } from './routes/admin/analytics/pillars'
import { Route as AdminAnalyticsInvestmentRouteImport } from './routes/admin/analytics/investment'
import { Route as AdminAnalyticsHoursRouteImport } from './routes/admin/analytics/hours'
import { Route as AdminAnalyticsExecutiveRouteImport } from './routes/admin/analytics/executive'
import { Route as AdminAnalyticsEffectivenessRouteImport } from './routes/admin/analytics/effectiveness'
import { Route as AdminAnalyticsCoverageRouteImport } from './routes/admin/analytics/coverage'
import { Route as AdminAnalyticsChampionsRouteImport } from './routes/admin/analytics/champions'
import { Route as AdminAnalyticsCertificationsRouteImport } from './routes/admin/analytics/certifications'
import { Route as AdminAnalyticsApprenticeRouteImport } from './routes/admin/analytics/apprentice'
import { Route as AdminAnalyticsAiRouteImport } from './routes/admin/analytics/ai'
import { Route as AdminAnalyticsAnalyticsIndexRouteImport } from './routes/admin/analytics/analytics/index'
import { Route as StudentResultsSlugIdRouteImport } from './routes/student/results/$slug/$id'
import { Route as AdminSubmodulesSubmoduleIdContentRouteImport } from './routes/admin/submodules/$submoduleId/content'

const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerIndexRoute = TrainerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainerRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrainerSettingsRoute = TrainerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerReportsRoute = TrainerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerLeaderboardRoute = TrainerLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerEventsRoute = TrainerEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerEvaluationRoute = TrainerEvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerAssessmentBuilderRoute =
  TrainerAssessmentBuilderRouteImport.update({
    id: '/assessment-builder',
    path: '/assessment-builder',
    getParentRoute: () => TrainerRoute,
  } as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFeedbackRoute = StudentFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => StudentRoute,
} as any)
const StudentEventsRoute = StudentEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentBatchesRoute = StudentBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssessmentsRoute = StudentAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => StudentRoute,
} as any)
const AdminTrainerRoute = AdminTrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganiserRoute = AdminOrganiserRouteImport.update({
  id: '/organiser',
  path: '/organiser',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCurriculumRoute = AdminCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBatchesRoute = AdminBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssessmentsRoute = AdminAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AdminRoute,
} as any)
const TrainerBatchesIndexRoute = TrainerBatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => TrainerRoute,
} as any)
const StudentResultsIndexRoute = StudentResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCurriculumIndexRoute = AdminCurriculumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCurriculumRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBatchesIndexRoute = AdminBatchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBatchesRoute,
} as any)
const AdminAssessmentsIndexRoute = AdminAssessmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAssessmentsRoute,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AdminRoute,
} as any)
const TrainerBatchesIdRoute = TrainerBatchesIdRouteImport.update({
  id: '/batches/$id',
  path: '/batches/$id',
  getParentRoute: () => TrainerRoute,
} as any)
const StudentTakeSlugRoute = StudentTakeSlugRouteImport.update({
  id: '/take/$slug',
  path: '/take/$slug',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTakeCodingSlugRoute = StudentTakeCodingSlugRouteImport.update({
  id: '/take-coding/$slug',
  path: '/take-coding/$slug',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCourseCourseIdRoute = StudentCourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCertificateSubmissionIdRoute =
  StudentCertificateSubmissionIdRouteImport.update({
    id: '/certificate/$submissionId',
    path: '/certificate/$submissionId',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentAssessmentAssessmentIdRoute =
  StudentAssessmentAssessmentIdRouteImport.update({
    id: '/assessment/$assessmentId',
    path: '/assessment/$assessmentId',
    getParentRoute: () => StudentRoute,
  } as any)
const AdminCurriculumCourseIdRoute = AdminCurriculumCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AdminCurriculumRoute,
} as any)
const AdminCoursesBuilderRoute = AdminCoursesBuilderRouteImport.update({
  id: '/courses/builder',
  path: '/courses/builder',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesCourseSlugRoute = AdminCoursesCourseSlugRouteImport.update({
  id: '/courses/$courseSlug',
  path: '/courses/$courseSlug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesCategorySlugRoute =
  AdminCategoriesCategorySlugRouteImport.update({
    id: '/categories/$categorySlug',
    path: '/categories/$categorySlug',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBatchesTrainersRoute = AdminBatchesTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => AdminBatchesRoute,
} as any)
const AdminBatchesAnalyticsRoute = AdminBatchesAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminBatchesRoute,
} as any)
const AdminBatchesAllocationsRoute = AdminBatchesAllocationsRouteImport.update({
  id: '/allocations',
  path: '/allocations',
  getParentRoute: () => AdminBatchesRoute,
} as any)
const AdminBatchesAllocateRoute = AdminBatchesAllocateRouteImport.update({
  id: '/allocate',
  path: '/allocate',
  getParentRoute: () => AdminBatchesRoute,
} as any)
const AdminBatchesBatchIdRoute = AdminBatchesBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => AdminBatchesRoute,
} as any)
const AdminAssessmentsAnalyticsRoute =
  AdminAssessmentsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AdminAssessmentsRoute,
  } as any)
const AdminAssessmentsAssessmentIdRoute =
  AdminAssessmentsAssessmentIdRouteImport.update({
    id: '/$assessmentId',
    path: '/$assessmentId',
    getParentRoute: () => AdminAssessmentsRoute,
  } as any)
const AdminAnalyticsTrendsRoute = AdminAnalyticsTrendsRouteImport.update({
  id: '/analytics/trends',
  path: '/analytics/trends',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsSkillGapRoute = AdminAnalyticsSkillGapRouteImport.update({
  id: '/analytics/skill-gap',
  path: '/analytics/skill-gap',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRecommendationsRoute =
  AdminAnalyticsRecommendationsRouteImport.update({
    id: '/analytics/recommendations',
    path: '/analytics/recommendations',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAnalyticsProgramsRoute = AdminAnalyticsProgramsRouteImport.update({
  id: '/analytics/programs',
  path: '/analytics/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsPredictiveRoute =
  AdminAnalyticsPredictiveRouteImport.update({
    id: '/analytics/predictive',
    path: '/analytics/predictive',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAnalyticsPillarsRoute = AdminAnalyticsPillarsRouteImport.update({
  id: '/analytics/pillars',
  path: '/analytics/pillars',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsInvestmentRoute =
  AdminAnalyticsInvestmentRouteImport.update({
    id: '/analytics/investment',
    path: '/analytics/investment',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAnalyticsHoursRoute = AdminAnalyticsHoursRouteImport.update({
  id: '/analytics/hours',
  path: '/analytics/hours',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsExecutiveRoute = AdminAnalyticsExecutiveRouteImport.update({
  id: '/analytics/executive',
  path: '/analytics/executive',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsEffectivenessRoute =
  AdminAnalyticsEffectivenessRouteImport.update({
    id: '/analytics/effectiveness',
    path: '/analytics/effectiveness',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAnalyticsCoverageRoute = AdminAnalyticsCoverageRouteImport.update({
  id: '/analytics/coverage',
  path: '/analytics/coverage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsChampionsRoute = AdminAnalyticsChampionsRouteImport.update({
  id: '/analytics/champions',
  path: '/analytics/champions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsCertificationsRoute =
  AdminAnalyticsCertificationsRouteImport.update({
    id: '/analytics/certifications',
    path: '/analytics/certifications',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAnalyticsApprenticeRoute =
  AdminAnalyticsApprenticeRouteImport.update({
    id: '/analytics/apprentice',
    path: '/analytics/apprentice',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAnalyticsAiRoute = AdminAnalyticsAiRouteImport.update({
  id: '/analytics/ai',
  path: '/analytics/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsAnalyticsIndexRoute =
  AdminAnalyticsAnalyticsIndexRouteImport.update({
    id: '/analytics/analytics/',
    path: '/analytics/analytics/',
    getParentRoute: () => AdminRoute,
  } as any)
const StudentResultsSlugIdRoute = StudentResultsSlugIdRouteImport.update({
  id: '/results/$slug/$id',
  path: '/results/$slug/$id',
  getParentRoute: () => StudentRoute,
} as any)
const AdminSubmodulesSubmoduleIdContentRoute =
  AdminSubmodulesSubmoduleIdContentRouteImport.update({
    id: '/submodules/$submoduleId/content',
    path: '/submodules/$submoduleId/content',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/student': typeof StudentRouteWithChildren
  '/trainer': typeof TrainerRouteWithChildren
  '/admin/assessments': typeof AdminAssessmentsRouteWithChildren
  '/admin/batches': typeof AdminBatchesRouteWithChildren
  '/admin/curriculum': typeof AdminCurriculumRouteWithChildren
  '/admin/organiser': typeof AdminOrganiserRoute
  '/admin/trainer': typeof AdminTrainerRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/batches': typeof StudentBatchesRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/events': typeof StudentEventsRoute
  '/student/feedback': typeof StudentFeedbackRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/trainer/assessment-builder': typeof TrainerAssessmentBuilderRoute
  '/trainer/evaluation': typeof TrainerEvaluationRoute
  '/trainer/events': typeof TrainerEventsRoute
  '/trainer/leaderboard': typeof TrainerLeaderboardRoute
  '/trainer/reports': typeof TrainerReportsRoute
  '/trainer/settings': typeof TrainerSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/trainer/': typeof TrainerIndexRoute
  '/admin/analytics/ai': typeof AdminAnalyticsAiRoute
  '/admin/analytics/apprentice': typeof AdminAnalyticsApprenticeRoute
  '/admin/analytics/certifications': typeof AdminAnalyticsCertificationsRoute
  '/admin/analytics/champions': typeof AdminAnalyticsChampionsRoute
  '/admin/analytics/coverage': typeof AdminAnalyticsCoverageRoute
  '/admin/analytics/effectiveness': typeof AdminAnalyticsEffectivenessRoute
  '/admin/analytics/executive': typeof AdminAnalyticsExecutiveRoute
  '/admin/analytics/hours': typeof AdminAnalyticsHoursRoute
  '/admin/analytics/investment': typeof AdminAnalyticsInvestmentRoute
  '/admin/analytics/pillars': typeof AdminAnalyticsPillarsRoute
  '/admin/analytics/predictive': typeof AdminAnalyticsPredictiveRoute
  '/admin/analytics/programs': typeof AdminAnalyticsProgramsRoute
  '/admin/analytics/recommendations': typeof AdminAnalyticsRecommendationsRoute
  '/admin/analytics/skill-gap': typeof AdminAnalyticsSkillGapRoute
  '/admin/analytics/trends': typeof AdminAnalyticsTrendsRoute
  '/admin/assessments/$assessmentId': typeof AdminAssessmentsAssessmentIdRoute
  '/admin/assessments/analytics': typeof AdminAssessmentsAnalyticsRoute
  '/admin/batches/$batchId': typeof AdminBatchesBatchIdRoute
  '/admin/batches/allocate': typeof AdminBatchesAllocateRoute
  '/admin/batches/allocations': typeof AdminBatchesAllocationsRoute
  '/admin/batches/analytics': typeof AdminBatchesAnalyticsRoute
  '/admin/batches/trainers': typeof AdminBatchesTrainersRoute
  '/admin/categories/$categorySlug': typeof AdminCategoriesCategorySlugRoute
  '/admin/courses/$courseSlug': typeof AdminCoursesCourseSlugRoute
  '/admin/courses/builder': typeof AdminCoursesBuilderRoute
  '/admin/curriculum/$courseId': typeof AdminCurriculumCourseIdRoute
  '/student/assessment/$assessmentId': typeof StudentAssessmentAssessmentIdRoute
  '/student/certificate/$submissionId': typeof StudentCertificateSubmissionIdRoute
  '/student/course/$courseId': typeof StudentCourseCourseIdRoute
  '/student/take-coding/$slug': typeof StudentTakeCodingSlugRoute
  '/student/take/$slug': typeof StudentTakeSlugRoute
  '/trainer/batches/$id': typeof TrainerBatchesIdRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/assessments/': typeof AdminAssessmentsIndexRoute
  '/admin/batches/': typeof AdminBatchesIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/curriculum/': typeof AdminCurriculumIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/student/results/': typeof StudentResultsIndexRoute
  '/trainer/batches/': typeof TrainerBatchesIndexRoute
  '/admin/submodules/$submoduleId/content': typeof AdminSubmodulesSubmoduleIdContentRoute
  '/student/results/$slug/$id': typeof StudentResultsSlugIdRoute
  '/admin/analytics/analytics/': typeof AdminAnalyticsAnalyticsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/admin/organiser': typeof AdminOrganiserRoute
  '/admin/trainer': typeof AdminTrainerRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/batches': typeof StudentBatchesRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/events': typeof StudentEventsRoute
  '/student/feedback': typeof StudentFeedbackRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/trainer/assessment-builder': typeof TrainerAssessmentBuilderRoute
  '/trainer/evaluation': typeof TrainerEvaluationRoute
  '/trainer/events': typeof TrainerEventsRoute
  '/trainer/leaderboard': typeof TrainerLeaderboardRoute
  '/trainer/reports': typeof TrainerReportsRoute
  '/trainer/settings': typeof TrainerSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/trainer': typeof TrainerIndexRoute
  '/admin/analytics/ai': typeof AdminAnalyticsAiRoute
  '/admin/analytics/apprentice': typeof AdminAnalyticsApprenticeRoute
  '/admin/analytics/certifications': typeof AdminAnalyticsCertificationsRoute
  '/admin/analytics/champions': typeof AdminAnalyticsChampionsRoute
  '/admin/analytics/coverage': typeof AdminAnalyticsCoverageRoute
  '/admin/analytics/effectiveness': typeof AdminAnalyticsEffectivenessRoute
  '/admin/analytics/executive': typeof AdminAnalyticsExecutiveRoute
  '/admin/analytics/hours': typeof AdminAnalyticsHoursRoute
  '/admin/analytics/investment': typeof AdminAnalyticsInvestmentRoute
  '/admin/analytics/pillars': typeof AdminAnalyticsPillarsRoute
  '/admin/analytics/predictive': typeof AdminAnalyticsPredictiveRoute
  '/admin/analytics/programs': typeof AdminAnalyticsProgramsRoute
  '/admin/analytics/recommendations': typeof AdminAnalyticsRecommendationsRoute
  '/admin/analytics/skill-gap': typeof AdminAnalyticsSkillGapRoute
  '/admin/analytics/trends': typeof AdminAnalyticsTrendsRoute
  '/admin/assessments/$assessmentId': typeof AdminAssessmentsAssessmentIdRoute
  '/admin/assessments/analytics': typeof AdminAssessmentsAnalyticsRoute
  '/admin/batches/$batchId': typeof AdminBatchesBatchIdRoute
  '/admin/batches/allocate': typeof AdminBatchesAllocateRoute
  '/admin/batches/allocations': typeof AdminBatchesAllocationsRoute
  '/admin/batches/analytics': typeof AdminBatchesAnalyticsRoute
  '/admin/batches/trainers': typeof AdminBatchesTrainersRoute
  '/admin/categories/$categorySlug': typeof AdminCategoriesCategorySlugRoute
  '/admin/courses/$courseSlug': typeof AdminCoursesCourseSlugRoute
  '/admin/courses/builder': typeof AdminCoursesBuilderRoute
  '/admin/curriculum/$courseId': typeof AdminCurriculumCourseIdRoute
  '/student/assessment/$assessmentId': typeof StudentAssessmentAssessmentIdRoute
  '/student/certificate/$submissionId': typeof StudentCertificateSubmissionIdRoute
  '/student/course/$courseId': typeof StudentCourseCourseIdRoute
  '/student/take-coding/$slug': typeof StudentTakeCodingSlugRoute
  '/student/take/$slug': typeof StudentTakeSlugRoute
  '/trainer/batches/$id': typeof TrainerBatchesIdRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/assessments': typeof AdminAssessmentsIndexRoute
  '/admin/batches': typeof AdminBatchesIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/curriculum': typeof AdminCurriculumIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/student/results': typeof StudentResultsIndexRoute
  '/trainer/batches': typeof TrainerBatchesIndexRoute
  '/admin/submodules/$submoduleId/content': typeof AdminSubmodulesSubmoduleIdContentRoute
  '/student/results/$slug/$id': typeof StudentResultsSlugIdRoute
  '/admin/analytics/analytics': typeof AdminAnalyticsAnalyticsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/student': typeof StudentRouteWithChildren
  '/trainer': typeof TrainerRouteWithChildren
  '/admin/assessments': typeof AdminAssessmentsRouteWithChildren
  '/admin/batches': typeof AdminBatchesRouteWithChildren
  '/admin/curriculum': typeof AdminCurriculumRouteWithChildren
  '/admin/organiser': typeof AdminOrganiserRoute
  '/admin/trainer': typeof AdminTrainerRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/batches': typeof StudentBatchesRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/events': typeof StudentEventsRoute
  '/student/feedback': typeof StudentFeedbackRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/trainer/assessment-builder': typeof TrainerAssessmentBuilderRoute
  '/trainer/evaluation': typeof TrainerEvaluationRoute
  '/trainer/events': typeof TrainerEventsRoute
  '/trainer/leaderboard': typeof TrainerLeaderboardRoute
  '/trainer/reports': typeof TrainerReportsRoute
  '/trainer/settings': typeof TrainerSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/trainer/': typeof TrainerIndexRoute
  '/admin/analytics/ai': typeof AdminAnalyticsAiRoute
  '/admin/analytics/apprentice': typeof AdminAnalyticsApprenticeRoute
  '/admin/analytics/certifications': typeof AdminAnalyticsCertificationsRoute
  '/admin/analytics/champions': typeof AdminAnalyticsChampionsRoute
  '/admin/analytics/coverage': typeof AdminAnalyticsCoverageRoute
  '/admin/analytics/effectiveness': typeof AdminAnalyticsEffectivenessRoute
  '/admin/analytics/executive': typeof AdminAnalyticsExecutiveRoute
  '/admin/analytics/hours': typeof AdminAnalyticsHoursRoute
  '/admin/analytics/investment': typeof AdminAnalyticsInvestmentRoute
  '/admin/analytics/pillars': typeof AdminAnalyticsPillarsRoute
  '/admin/analytics/predictive': typeof AdminAnalyticsPredictiveRoute
  '/admin/analytics/programs': typeof AdminAnalyticsProgramsRoute
  '/admin/analytics/recommendations': typeof AdminAnalyticsRecommendationsRoute
  '/admin/analytics/skill-gap': typeof AdminAnalyticsSkillGapRoute
  '/admin/analytics/trends': typeof AdminAnalyticsTrendsRoute
  '/admin/assessments/$assessmentId': typeof AdminAssessmentsAssessmentIdRoute
  '/admin/assessments/analytics': typeof AdminAssessmentsAnalyticsRoute
  '/admin/batches/$batchId': typeof AdminBatchesBatchIdRoute
  '/admin/batches/allocate': typeof AdminBatchesAllocateRoute
  '/admin/batches/allocations': typeof AdminBatchesAllocationsRoute
  '/admin/batches/analytics': typeof AdminBatchesAnalyticsRoute
  '/admin/batches/trainers': typeof AdminBatchesTrainersRoute
  '/admin/categories/$categorySlug': typeof AdminCategoriesCategorySlugRoute
  '/admin/courses/$courseSlug': typeof AdminCoursesCourseSlugRoute
  '/admin/courses/builder': typeof AdminCoursesBuilderRoute
  '/admin/curriculum/$courseId': typeof AdminCurriculumCourseIdRoute
  '/student/assessment/$assessmentId': typeof StudentAssessmentAssessmentIdRoute
  '/student/certificate/$submissionId': typeof StudentCertificateSubmissionIdRoute
  '/student/course/$courseId': typeof StudentCourseCourseIdRoute
  '/student/take-coding/$slug': typeof StudentTakeCodingSlugRoute
  '/student/take/$slug': typeof StudentTakeSlugRoute
  '/trainer/batches/$id': typeof TrainerBatchesIdRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/assessments/': typeof AdminAssessmentsIndexRoute
  '/admin/batches/': typeof AdminBatchesIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/curriculum/': typeof AdminCurriculumIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/student/results/': typeof StudentResultsIndexRoute
  '/trainer/batches/': typeof TrainerBatchesIndexRoute
  '/admin/submodules/$submoduleId/content': typeof AdminSubmodulesSubmoduleIdContentRoute
  '/student/results/$slug/$id': typeof StudentResultsSlugIdRoute
  '/admin/analytics/analytics/': typeof AdminAnalyticsAnalyticsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/student'
    | '/trainer'
    | '/admin/assessments'
    | '/admin/batches'
    | '/admin/curriculum'
    | '/admin/organiser'
    | '/admin/trainer'
    | '/student/assessments'
    | '/student/batches'
    | '/student/courses'
    | '/student/events'
    | '/student/feedback'
    | '/student/notifications'
    | '/student/profile'
    | '/trainer/assessment-builder'
    | '/trainer/evaluation'
    | '/trainer/events'
    | '/trainer/leaderboard'
    | '/trainer/reports'
    | '/trainer/settings'
    | '/admin/'
    | '/student/'
    | '/trainer/'
    | '/admin/analytics/ai'
    | '/admin/analytics/apprentice'
    | '/admin/analytics/certifications'
    | '/admin/analytics/champions'
    | '/admin/analytics/coverage'
    | '/admin/analytics/effectiveness'
    | '/admin/analytics/executive'
    | '/admin/analytics/hours'
    | '/admin/analytics/investment'
    | '/admin/analytics/pillars'
    | '/admin/analytics/predictive'
    | '/admin/analytics/programs'
    | '/admin/analytics/recommendations'
    | '/admin/analytics/skill-gap'
    | '/admin/analytics/trends'
    | '/admin/assessments/$assessmentId'
    | '/admin/assessments/analytics'
    | '/admin/batches/$batchId'
    | '/admin/batches/allocate'
    | '/admin/batches/allocations'
    | '/admin/batches/analytics'
    | '/admin/batches/trainers'
    | '/admin/categories/$categorySlug'
    | '/admin/courses/$courseSlug'
    | '/admin/courses/builder'
    | '/admin/curriculum/$courseId'
    | '/student/assessment/$assessmentId'
    | '/student/certificate/$submissionId'
    | '/student/course/$courseId'
    | '/student/take-coding/$slug'
    | '/student/take/$slug'
    | '/trainer/batches/$id'
    | '/admin/analytics/'
    | '/admin/assessments/'
    | '/admin/batches/'
    | '/admin/categories/'
    | '/admin/courses/'
    | '/admin/curriculum/'
    | '/admin/events/'
    | '/student/results/'
    | '/trainer/batches/'
    | '/admin/submodules/$submoduleId/content'
    | '/student/results/$slug/$id'
    | '/admin/analytics/analytics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/admin/organiser'
    | '/admin/trainer'
    | '/student/assessments'
    | '/student/batches'
    | '/student/courses'
    | '/student/events'
    | '/student/feedback'
    | '/student/notifications'
    | '/student/profile'
    | '/trainer/assessment-builder'
    | '/trainer/evaluation'
    | '/trainer/events'
    | '/trainer/leaderboard'
    | '/trainer/reports'
    | '/trainer/settings'
    | '/admin'
    | '/student'
    | '/trainer'
    | '/admin/analytics/ai'
    | '/admin/analytics/apprentice'
    | '/admin/analytics/certifications'
    | '/admin/analytics/champions'
    | '/admin/analytics/coverage'
    | '/admin/analytics/effectiveness'
    | '/admin/analytics/executive'
    | '/admin/analytics/hours'
    | '/admin/analytics/investment'
    | '/admin/analytics/pillars'
    | '/admin/analytics/predictive'
    | '/admin/analytics/programs'
    | '/admin/analytics/recommendations'
    | '/admin/analytics/skill-gap'
    | '/admin/analytics/trends'
    | '/admin/assessments/$assessmentId'
    | '/admin/assessments/analytics'
    | '/admin/batches/$batchId'
    | '/admin/batches/allocate'
    | '/admin/batches/allocations'
    | '/admin/batches/analytics'
    | '/admin/batches/trainers'
    | '/admin/categories/$categorySlug'
    | '/admin/courses/$courseSlug'
    | '/admin/courses/builder'
    | '/admin/curriculum/$courseId'
    | '/student/assessment/$assessmentId'
    | '/student/certificate/$submissionId'
    | '/student/course/$courseId'
    | '/student/take-coding/$slug'
    | '/student/take/$slug'
    | '/trainer/batches/$id'
    | '/admin/analytics'
    | '/admin/assessments'
    | '/admin/batches'
    | '/admin/categories'
    | '/admin/courses'
    | '/admin/curriculum'
    | '/admin/events'
    | '/student/results'
    | '/trainer/batches'
    | '/admin/submodules/$submoduleId/content'
    | '/student/results/$slug/$id'
    | '/admin/analytics/analytics'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/student'
    | '/trainer'
    | '/admin/assessments'
    | '/admin/batches'
    | '/admin/curriculum'
    | '/admin/organiser'
    | '/admin/trainer'
    | '/student/assessments'
    | '/student/batches'
    | '/student/courses'
    | '/student/events'
    | '/student/feedback'
    | '/student/notifications'
    | '/student/profile'
    | '/trainer/assessment-builder'
    | '/trainer/evaluation'
    | '/trainer/events'
    | '/trainer/leaderboard'
    | '/trainer/reports'
    | '/trainer/settings'
    | '/admin/'
    | '/student/'
    | '/trainer/'
    | '/admin/analytics/ai'
    | '/admin/analytics/apprentice'
    | '/admin/analytics/certifications'
    | '/admin/analytics/champions'
    | '/admin/analytics/coverage'
    | '/admin/analytics/effectiveness'
    | '/admin/analytics/executive'
    | '/admin/analytics/hours'
    | '/admin/analytics/investment'
    | '/admin/analytics/pillars'
    | '/admin/analytics/predictive'
    | '/admin/analytics/programs'
    | '/admin/analytics/recommendations'
    | '/admin/analytics/skill-gap'
    | '/admin/analytics/trends'
    | '/admin/assessments/$assessmentId'
    | '/admin/assessments/analytics'
    | '/admin/batches/$batchId'
    | '/admin/batches/allocate'
    | '/admin/batches/allocations'
    | '/admin/batches/analytics'
    | '/admin/batches/trainers'
    | '/admin/categories/$categorySlug'
    | '/admin/courses/$courseSlug'
    | '/admin/courses/builder'
    | '/admin/curriculum/$courseId'
    | '/student/assessment/$assessmentId'
    | '/student/certificate/$submissionId'
    | '/student/course/$courseId'
    | '/student/take-coding/$slug'
    | '/student/take/$slug'
    | '/trainer/batches/$id'
    | '/admin/analytics/'
    | '/admin/assessments/'
    | '/admin/batches/'
    | '/admin/categories/'
    | '/admin/courses/'
    | '/admin/curriculum/'
    | '/admin/events/'
    | '/student/results/'
    | '/trainer/batches/'
    | '/admin/submodules/$submoduleId/content'
    | '/student/results/$slug/$id'
    | '/admin/analytics/analytics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  StudentRoute: typeof StudentRouteWithChildren
  TrainerRoute: typeof TrainerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/': {
      id: '/trainer/'
      path: '/'
      fullPath: '/trainer/'
      preLoaderRoute: typeof TrainerIndexRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/trainer/settings': {
      id: '/trainer/settings'
      path: '/settings'
      fullPath: '/trainer/settings'
      preLoaderRoute: typeof TrainerSettingsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/reports': {
      id: '/trainer/reports'
      path: '/reports'
      fullPath: '/trainer/reports'
      preLoaderRoute: typeof TrainerReportsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/leaderboard': {
      id: '/trainer/leaderboard'
      path: '/leaderboard'
      fullPath: '/trainer/leaderboard'
      preLoaderRoute: typeof TrainerLeaderboardRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/events': {
      id: '/trainer/events'
      path: '/events'
      fullPath: '/trainer/events'
      preLoaderRoute: typeof TrainerEventsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/evaluation': {
      id: '/trainer/evaluation'
      path: '/evaluation'
      fullPath: '/trainer/evaluation'
      preLoaderRoute: typeof TrainerEvaluationRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/assessment-builder': {
      id: '/trainer/assessment-builder'
      path: '/assessment-builder'
      fullPath: '/trainer/assessment-builder'
      preLoaderRoute: typeof TrainerAssessmentBuilderRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/feedback': {
      id: '/student/feedback'
      path: '/feedback'
      fullPath: '/student/feedback'
      preLoaderRoute: typeof StudentFeedbackRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/events': {
      id: '/student/events'
      path: '/events'
      fullPath: '/student/events'
      preLoaderRoute: typeof StudentEventsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/batches': {
      id: '/student/batches'
      path: '/batches'
      fullPath: '/student/batches'
      preLoaderRoute: typeof StudentBatchesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assessments': {
      id: '/student/assessments'
      path: '/assessments'
      fullPath: '/student/assessments'
      preLoaderRoute: typeof StudentAssessmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/trainer': {
      id: '/admin/trainer'
      path: '/trainer'
      fullPath: '/admin/trainer'
      preLoaderRoute: typeof AdminTrainerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organiser': {
      id: '/admin/organiser'
      path: '/organiser'
      fullPath: '/admin/organiser'
      preLoaderRoute: typeof AdminOrganiserRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/curriculum': {
      id: '/admin/curriculum'
      path: '/curriculum'
      fullPath: '/admin/curriculum'
      preLoaderRoute: typeof AdminCurriculumRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/batches': {
      id: '/admin/batches'
      path: '/batches'
      fullPath: '/admin/batches'
      preLoaderRoute: typeof AdminBatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assessments': {
      id: '/admin/assessments'
      path: '/assessments'
      fullPath: '/admin/assessments'
      preLoaderRoute: typeof AdminAssessmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/trainer/batches/': {
      id: '/trainer/batches/'
      path: '/batches'
      fullPath: '/trainer/batches/'
      preLoaderRoute: typeof TrainerBatchesIndexRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/student/results/': {
      id: '/student/results/'
      path: '/results'
      fullPath: '/student/results/'
      preLoaderRoute: typeof StudentResultsIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/curriculum/': {
      id: '/admin/curriculum/'
      path: '/'
      fullPath: '/admin/curriculum/'
      preLoaderRoute: typeof AdminCurriculumIndexRouteImport
      parentRoute: typeof AdminCurriculumRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/batches/': {
      id: '/admin/batches/'
      path: '/'
      fullPath: '/admin/batches/'
      preLoaderRoute: typeof AdminBatchesIndexRouteImport
      parentRoute: typeof AdminBatchesRoute
    }
    '/admin/assessments/': {
      id: '/admin/assessments/'
      path: '/'
      fullPath: '/admin/assessments/'
      preLoaderRoute: typeof AdminAssessmentsIndexRouteImport
      parentRoute: typeof AdminAssessmentsRoute
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/analytics'
      fullPath: '/admin/analytics/'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/trainer/batches/$id': {
      id: '/trainer/batches/$id'
      path: '/batches/$id'
      fullPath: '/trainer/batches/$id'
      preLoaderRoute: typeof TrainerBatchesIdRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/student/take/$slug': {
      id: '/student/take/$slug'
      path: '/take/$slug'
      fullPath: '/student/take/$slug'
      preLoaderRoute: typeof StudentTakeSlugRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/take-coding/$slug': {
      id: '/student/take-coding/$slug'
      path: '/take-coding/$slug'
      fullPath: '/student/take-coding/$slug'
      preLoaderRoute: typeof StudentTakeCodingSlugRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/course/$courseId': {
      id: '/student/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/student/course/$courseId'
      preLoaderRoute: typeof StudentCourseCourseIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/certificate/$submissionId': {
      id: '/student/certificate/$submissionId'
      path: '/certificate/$submissionId'
      fullPath: '/student/certificate/$submissionId'
      preLoaderRoute: typeof StudentCertificateSubmissionIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assessment/$assessmentId': {
      id: '/student/assessment/$assessmentId'
      path: '/assessment/$assessmentId'
      fullPath: '/student/assessment/$assessmentId'
      preLoaderRoute: typeof StudentAssessmentAssessmentIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/curriculum/$courseId': {
      id: '/admin/curriculum/$courseId'
      path: '/$courseId'
      fullPath: '/admin/curriculum/$courseId'
      preLoaderRoute: typeof AdminCurriculumCourseIdRouteImport
      parentRoute: typeof AdminCurriculumRoute
    }
    '/admin/courses/builder': {
      id: '/admin/courses/builder'
      path: '/courses/builder'
      fullPath: '/admin/courses/builder'
      preLoaderRoute: typeof AdminCoursesBuilderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/$courseSlug': {
      id: '/admin/courses/$courseSlug'
      path: '/courses/$courseSlug'
      fullPath: '/admin/courses/$courseSlug'
      preLoaderRoute: typeof AdminCoursesCourseSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/$categorySlug': {
      id: '/admin/categories/$categorySlug'
      path: '/categories/$categorySlug'
      fullPath: '/admin/categories/$categorySlug'
      preLoaderRoute: typeof AdminCategoriesCategorySlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/batches/trainers': {
      id: '/admin/batches/trainers'
      path: '/trainers'
      fullPath: '/admin/batches/trainers'
      preLoaderRoute: typeof AdminBatchesTrainersRouteImport
      parentRoute: typeof AdminBatchesRoute
    }
    '/admin/batches/analytics': {
      id: '/admin/batches/analytics'
      path: '/analytics'
      fullPath: '/admin/batches/analytics'
      preLoaderRoute: typeof AdminBatchesAnalyticsRouteImport
      parentRoute: typeof AdminBatchesRoute
    }
    '/admin/batches/allocations': {
      id: '/admin/batches/allocations'
      path: '/allocations'
      fullPath: '/admin/batches/allocations'
      preLoaderRoute: typeof AdminBatchesAllocationsRouteImport
      parentRoute: typeof AdminBatchesRoute
    }
    '/admin/batches/allocate': {
      id: '/admin/batches/allocate'
      path: '/allocate'
      fullPath: '/admin/batches/allocate'
      preLoaderRoute: typeof AdminBatchesAllocateRouteImport
      parentRoute: typeof AdminBatchesRoute
    }
    '/admin/batches/$batchId': {
      id: '/admin/batches/$batchId'
      path: '/$batchId'
      fullPath: '/admin/batches/$batchId'
      preLoaderRoute: typeof AdminBatchesBatchIdRouteImport
      parentRoute: typeof AdminBatchesRoute
    }
    '/admin/assessments/analytics': {
      id: '/admin/assessments/analytics'
      path: '/analytics'
      fullPath: '/admin/assessments/analytics'
      preLoaderRoute: typeof AdminAssessmentsAnalyticsRouteImport
      parentRoute: typeof AdminAssessmentsRoute
    }
    '/admin/assessments/$assessmentId': {
      id: '/admin/assessments/$assessmentId'
      path: '/$assessmentId'
      fullPath: '/admin/assessments/$assessmentId'
      preLoaderRoute: typeof AdminAssessmentsAssessmentIdRouteImport
      parentRoute: typeof AdminAssessmentsRoute
    }
    '/admin/analytics/trends': {
      id: '/admin/analytics/trends'
      path: '/analytics/trends'
      fullPath: '/admin/analytics/trends'
      preLoaderRoute: typeof AdminAnalyticsTrendsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/skill-gap': {
      id: '/admin/analytics/skill-gap'
      path: '/analytics/skill-gap'
      fullPath: '/admin/analytics/skill-gap'
      preLoaderRoute: typeof AdminAnalyticsSkillGapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/recommendations': {
      id: '/admin/analytics/recommendations'
      path: '/analytics/recommendations'
      fullPath: '/admin/analytics/recommendations'
      preLoaderRoute: typeof AdminAnalyticsRecommendationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/programs': {
      id: '/admin/analytics/programs'
      path: '/analytics/programs'
      fullPath: '/admin/analytics/programs'
      preLoaderRoute: typeof AdminAnalyticsProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/predictive': {
      id: '/admin/analytics/predictive'
      path: '/analytics/predictive'
      fullPath: '/admin/analytics/predictive'
      preLoaderRoute: typeof AdminAnalyticsPredictiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/pillars': {
      id: '/admin/analytics/pillars'
      path: '/analytics/pillars'
      fullPath: '/admin/analytics/pillars'
      preLoaderRoute: typeof AdminAnalyticsPillarsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/investment': {
      id: '/admin/analytics/investment'
      path: '/analytics/investment'
      fullPath: '/admin/analytics/investment'
      preLoaderRoute: typeof AdminAnalyticsInvestmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/hours': {
      id: '/admin/analytics/hours'
      path: '/analytics/hours'
      fullPath: '/admin/analytics/hours'
      preLoaderRoute: typeof AdminAnalyticsHoursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/executive': {
      id: '/admin/analytics/executive'
      path: '/analytics/executive'
      fullPath: '/admin/analytics/executive'
      preLoaderRoute: typeof AdminAnalyticsExecutiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/effectiveness': {
      id: '/admin/analytics/effectiveness'
      path: '/analytics/effectiveness'
      fullPath: '/admin/analytics/effectiveness'
      preLoaderRoute: typeof AdminAnalyticsEffectivenessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/coverage': {
      id: '/admin/analytics/coverage'
      path: '/analytics/coverage'
      fullPath: '/admin/analytics/coverage'
      preLoaderRoute: typeof AdminAnalyticsCoverageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/champions': {
      id: '/admin/analytics/champions'
      path: '/analytics/champions'
      fullPath: '/admin/analytics/champions'
      preLoaderRoute: typeof AdminAnalyticsChampionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/certifications': {
      id: '/admin/analytics/certifications'
      path: '/analytics/certifications'
      fullPath: '/admin/analytics/certifications'
      preLoaderRoute: typeof AdminAnalyticsCertificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/apprentice': {
      id: '/admin/analytics/apprentice'
      path: '/analytics/apprentice'
      fullPath: '/admin/analytics/apprentice'
      preLoaderRoute: typeof AdminAnalyticsApprenticeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/ai': {
      id: '/admin/analytics/ai'
      path: '/analytics/ai'
      fullPath: '/admin/analytics/ai'
      preLoaderRoute: typeof AdminAnalyticsAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/analytics/': {
      id: '/admin/analytics/analytics/'
      path: '/analytics/analytics'
      fullPath: '/admin/analytics/analytics/'
      preLoaderRoute: typeof AdminAnalyticsAnalyticsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/results/$slug/$id': {
      id: '/student/results/$slug/$id'
      path: '/results/$slug/$id'
      fullPath: '/student/results/$slug/$id'
      preLoaderRoute: typeof StudentResultsSlugIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/submodules/$submoduleId/content': {
      id: '/admin/submodules/$submoduleId/content'
      path: '/submodules/$submoduleId/content'
      fullPath: '/admin/submodules/$submoduleId/content'
      preLoaderRoute: typeof AdminSubmodulesSubmoduleIdContentRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminAssessmentsRouteChildren {
  AdminAssessmentsAssessmentIdRoute: typeof AdminAssessmentsAssessmentIdRoute
  AdminAssessmentsAnalyticsRoute: typeof AdminAssessmentsAnalyticsRoute
  AdminAssessmentsIndexRoute: typeof AdminAssessmentsIndexRoute
}

const AdminAssessmentsRouteChildren: AdminAssessmentsRouteChildren = {
  AdminAssessmentsAssessmentIdRoute: AdminAssessmentsAssessmentIdRoute,
  AdminAssessmentsAnalyticsRoute: AdminAssessmentsAnalyticsRoute,
  AdminAssessmentsIndexRoute: AdminAssessmentsIndexRoute,
}

const AdminAssessmentsRouteWithChildren =
  AdminAssessmentsRoute._addFileChildren(AdminAssessmentsRouteChildren)

interface AdminBatchesRouteChildren {
  AdminBatchesBatchIdRoute: typeof AdminBatchesBatchIdRoute
  AdminBatchesAllocateRoute: typeof AdminBatchesAllocateRoute
  AdminBatchesAllocationsRoute: typeof AdminBatchesAllocationsRoute
  AdminBatchesAnalyticsRoute: typeof AdminBatchesAnalyticsRoute
  AdminBatchesTrainersRoute: typeof AdminBatchesTrainersRoute
  AdminBatchesIndexRoute: typeof AdminBatchesIndexRoute
}

const AdminBatchesRouteChildren: AdminBatchesRouteChildren = {
  AdminBatchesBatchIdRoute: AdminBatchesBatchIdRoute,
  AdminBatchesAllocateRoute: AdminBatchesAllocateRoute,
  AdminBatchesAllocationsRoute: AdminBatchesAllocationsRoute,
  AdminBatchesAnalyticsRoute: AdminBatchesAnalyticsRoute,
  AdminBatchesTrainersRoute: AdminBatchesTrainersRoute,
  AdminBatchesIndexRoute: AdminBatchesIndexRoute,
}

const AdminBatchesRouteWithChildren = AdminBatchesRoute._addFileChildren(
  AdminBatchesRouteChildren,
)

interface AdminCurriculumRouteChildren {
  AdminCurriculumCourseIdRoute: typeof AdminCurriculumCourseIdRoute
  AdminCurriculumIndexRoute: typeof AdminCurriculumIndexRoute
}

const AdminCurriculumRouteChildren: AdminCurriculumRouteChildren = {
  AdminCurriculumCourseIdRoute: AdminCurriculumCourseIdRoute,
  AdminCurriculumIndexRoute: AdminCurriculumIndexRoute,
}

const AdminCurriculumRouteWithChildren = AdminCurriculumRoute._addFileChildren(
  AdminCurriculumRouteChildren,
)

interface AdminRouteChildren {
  AdminAssessmentsRoute: typeof AdminAssessmentsRouteWithChildren
  AdminBatchesRoute: typeof AdminBatchesRouteWithChildren
  AdminCurriculumRoute: typeof AdminCurriculumRouteWithChildren
  AdminOrganiserRoute: typeof AdminOrganiserRoute
  AdminTrainerRoute: typeof AdminTrainerRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnalyticsAiRoute: typeof AdminAnalyticsAiRoute
  AdminAnalyticsApprenticeRoute: typeof AdminAnalyticsApprenticeRoute
  AdminAnalyticsCertificationsRoute: typeof AdminAnalyticsCertificationsRoute
  AdminAnalyticsChampionsRoute: typeof AdminAnalyticsChampionsRoute
  AdminAnalyticsCoverageRoute: typeof AdminAnalyticsCoverageRoute
  AdminAnalyticsEffectivenessRoute: typeof AdminAnalyticsEffectivenessRoute
  AdminAnalyticsExecutiveRoute: typeof AdminAnalyticsExecutiveRoute
  AdminAnalyticsHoursRoute: typeof AdminAnalyticsHoursRoute
  AdminAnalyticsInvestmentRoute: typeof AdminAnalyticsInvestmentRoute
  AdminAnalyticsPillarsRoute: typeof AdminAnalyticsPillarsRoute
  AdminAnalyticsPredictiveRoute: typeof AdminAnalyticsPredictiveRoute
  AdminAnalyticsProgramsRoute: typeof AdminAnalyticsProgramsRoute
  AdminAnalyticsRecommendationsRoute: typeof AdminAnalyticsRecommendationsRoute
  AdminAnalyticsSkillGapRoute: typeof AdminAnalyticsSkillGapRoute
  AdminAnalyticsTrendsRoute: typeof AdminAnalyticsTrendsRoute
  AdminCategoriesCategorySlugRoute: typeof AdminCategoriesCategorySlugRoute
  AdminCoursesCourseSlugRoute: typeof AdminCoursesCourseSlugRoute
  AdminCoursesBuilderRoute: typeof AdminCoursesBuilderRoute
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminSubmodulesSubmoduleIdContentRoute: typeof AdminSubmodulesSubmoduleIdContentRoute
  AdminAnalyticsAnalyticsIndexRoute: typeof AdminAnalyticsAnalyticsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssessmentsRoute: AdminAssessmentsRouteWithChildren,
  AdminBatchesRoute: AdminBatchesRouteWithChildren,
  AdminCurriculumRoute: AdminCurriculumRouteWithChildren,
  AdminOrganiserRoute: AdminOrganiserRoute,
  AdminTrainerRoute: AdminTrainerRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAnalyticsAiRoute: AdminAnalyticsAiRoute,
  AdminAnalyticsApprenticeRoute: AdminAnalyticsApprenticeRoute,
  AdminAnalyticsCertificationsRoute: AdminAnalyticsCertificationsRoute,
  AdminAnalyticsChampionsRoute: AdminAnalyticsChampionsRoute,
  AdminAnalyticsCoverageRoute: AdminAnalyticsCoverageRoute,
  AdminAnalyticsEffectivenessRoute: AdminAnalyticsEffectivenessRoute,
  AdminAnalyticsExecutiveRoute: AdminAnalyticsExecutiveRoute,
  AdminAnalyticsHoursRoute: AdminAnalyticsHoursRoute,
  AdminAnalyticsInvestmentRoute: AdminAnalyticsInvestmentRoute,
  AdminAnalyticsPillarsRoute: AdminAnalyticsPillarsRoute,
  AdminAnalyticsPredictiveRoute: AdminAnalyticsPredictiveRoute,
  AdminAnalyticsProgramsRoute: AdminAnalyticsProgramsRoute,
  AdminAnalyticsRecommendationsRoute: AdminAnalyticsRecommendationsRoute,
  AdminAnalyticsSkillGapRoute: AdminAnalyticsSkillGapRoute,
  AdminAnalyticsTrendsRoute: AdminAnalyticsTrendsRoute,
  AdminCategoriesCategorySlugRoute: AdminCategoriesCategorySlugRoute,
  AdminCoursesCourseSlugRoute: AdminCoursesCourseSlugRoute,
  AdminCoursesBuilderRoute: AdminCoursesBuilderRoute,
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminSubmodulesSubmoduleIdContentRoute:
    AdminSubmodulesSubmoduleIdContentRoute,
  AdminAnalyticsAnalyticsIndexRoute: AdminAnalyticsAnalyticsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentAssessmentsRoute: typeof StudentAssessmentsRoute
  StudentBatchesRoute: typeof StudentBatchesRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentEventsRoute: typeof StudentEventsRoute
  StudentFeedbackRoute: typeof StudentFeedbackRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentAssessmentAssessmentIdRoute: typeof StudentAssessmentAssessmentIdRoute
  StudentCertificateSubmissionIdRoute: typeof StudentCertificateSubmissionIdRoute
  StudentCourseCourseIdRoute: typeof StudentCourseCourseIdRoute
  StudentTakeCodingSlugRoute: typeof StudentTakeCodingSlugRoute
  StudentTakeSlugRoute: typeof StudentTakeSlugRoute
  StudentResultsIndexRoute: typeof StudentResultsIndexRoute
  StudentResultsSlugIdRoute: typeof StudentResultsSlugIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAssessmentsRoute: StudentAssessmentsRoute,
  StudentBatchesRoute: StudentBatchesRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentEventsRoute: StudentEventsRoute,
  StudentFeedbackRoute: StudentFeedbackRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentAssessmentAssessmentIdRoute: StudentAssessmentAssessmentIdRoute,
  StudentCertificateSubmissionIdRoute: StudentCertificateSubmissionIdRoute,
  StudentCourseCourseIdRoute: StudentCourseCourseIdRoute,
  StudentTakeCodingSlugRoute: StudentTakeCodingSlugRoute,
  StudentTakeSlugRoute: StudentTakeSlugRoute,
  StudentResultsIndexRoute: StudentResultsIndexRoute,
  StudentResultsSlugIdRoute: StudentResultsSlugIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TrainerRouteChildren {
  TrainerAssessmentBuilderRoute: typeof TrainerAssessmentBuilderRoute
  TrainerEvaluationRoute: typeof TrainerEvaluationRoute
  TrainerEventsRoute: typeof TrainerEventsRoute
  TrainerLeaderboardRoute: typeof TrainerLeaderboardRoute
  TrainerReportsRoute: typeof TrainerReportsRoute
  TrainerSettingsRoute: typeof TrainerSettingsRoute
  TrainerIndexRoute: typeof TrainerIndexRoute
  TrainerBatchesIdRoute: typeof TrainerBatchesIdRoute
  TrainerBatchesIndexRoute: typeof TrainerBatchesIndexRoute
}

const TrainerRouteChildren: TrainerRouteChildren = {
  TrainerAssessmentBuilderRoute: TrainerAssessmentBuilderRoute,
  TrainerEvaluationRoute: TrainerEvaluationRoute,
  TrainerEventsRoute: TrainerEventsRoute,
  TrainerLeaderboardRoute: TrainerLeaderboardRoute,
  TrainerReportsRoute: TrainerReportsRoute,
  TrainerSettingsRoute: TrainerSettingsRoute,
  TrainerIndexRoute: TrainerIndexRoute,
  TrainerBatchesIdRoute: TrainerBatchesIdRoute,
  TrainerBatchesIndexRoute: TrainerBatchesIndexRoute,
}

const TrainerRouteWithChildren =
  TrainerRoute._addFileChildren(TrainerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  StudentRoute: StudentRouteWithChildren,
  TrainerRoute: TrainerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.js'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
