/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutResultsRouteImport } from './routes/_layout/results'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutNotificationsRouteImport } from './routes/_layout/notifications'
import { Route as LayoutFeedbackRouteImport } from './routes/_layout/feedback'
import { Route as LayoutCoursesRouteImport } from './routes/_layout/courses'
import { Route as LayoutBatchesRouteImport } from './routes/_layout/batches'
import { Route as LayoutAssessmentsRouteImport } from './routes/_layout/assessments'
import { Route as LayoutCourseCourseIdRouteImport } from './routes/_layout/course/$courseId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResultsRoute = LayoutResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotificationsRoute = LayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFeedbackRoute = LayoutFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCoursesRoute = LayoutCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBatchesRoute = LayoutBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAssessmentsRoute = LayoutAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCourseCourseIdRoute = LayoutCourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/assessments': typeof LayoutAssessmentsRoute
  '/batches': typeof LayoutBatchesRoute
  '/courses': typeof LayoutCoursesRoute
  '/feedback': typeof LayoutFeedbackRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/profile': typeof LayoutProfileRoute
  '/results': typeof LayoutResultsRoute
  '/course/$courseId': typeof LayoutCourseCourseIdRoute
}
export interface FileRoutesByTo {
  '/assessments': typeof LayoutAssessmentsRoute
  '/batches': typeof LayoutBatchesRoute
  '/courses': typeof LayoutCoursesRoute
  '/feedback': typeof LayoutFeedbackRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/profile': typeof LayoutProfileRoute
  '/results': typeof LayoutResultsRoute
  '/': typeof LayoutIndexRoute
  '/course/$courseId': typeof LayoutCourseCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/assessments': typeof LayoutAssessmentsRoute
  '/_layout/batches': typeof LayoutBatchesRoute
  '/_layout/courses': typeof LayoutCoursesRoute
  '/_layout/feedback': typeof LayoutFeedbackRoute
  '/_layout/notifications': typeof LayoutNotificationsRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/results': typeof LayoutResultsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/course/$courseId': typeof LayoutCourseCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessments'
    | '/batches'
    | '/courses'
    | '/feedback'
    | '/notifications'
    | '/profile'
    | '/results'
    | '/course/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assessments'
    | '/batches'
    | '/courses'
    | '/feedback'
    | '/notifications'
    | '/profile'
    | '/results'
    | '/'
    | '/course/$courseId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/assessments'
    | '/_layout/batches'
    | '/_layout/courses'
    | '/_layout/feedback'
    | '/_layout/notifications'
    | '/_layout/profile'
    | '/_layout/results'
    | '/_layout/'
    | '/_layout/course/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/results': {
      id: '/_layout/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof LayoutResultsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications': {
      id: '/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof LayoutNotificationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/feedback': {
      id: '/_layout/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof LayoutFeedbackRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/courses': {
      id: '/_layout/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof LayoutCoursesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/batches': {
      id: '/_layout/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof LayoutBatchesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/assessments': {
      id: '/_layout/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof LayoutAssessmentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/course/$courseId': {
      id: '/_layout/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof LayoutCourseCourseIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAssessmentsRoute: typeof LayoutAssessmentsRoute
  LayoutBatchesRoute: typeof LayoutBatchesRoute
  LayoutCoursesRoute: typeof LayoutCoursesRoute
  LayoutFeedbackRoute: typeof LayoutFeedbackRoute
  LayoutNotificationsRoute: typeof LayoutNotificationsRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutResultsRoute: typeof LayoutResultsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCourseCourseIdRoute: typeof LayoutCourseCourseIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAssessmentsRoute: LayoutAssessmentsRoute,
  LayoutBatchesRoute: LayoutBatchesRoute,
  LayoutCoursesRoute: LayoutCoursesRoute,
  LayoutFeedbackRoute: LayoutFeedbackRoute,
  LayoutNotificationsRoute: LayoutNotificationsRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutResultsRoute: LayoutResultsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCourseCourseIdRoute: LayoutCourseCourseIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.js'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
