/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as StudentRouteImport } from './routes/student'
import { Route as OrganiserRouteImport } from './routes/organiser'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as StudentResultsRouteImport } from './routes/student/results'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as StudentNotificationsRouteImport } from './routes/student/notifications'
import { Route as StudentFeedbackRouteImport } from './routes/student/feedback'
import { Route as StudentCoursesRouteImport } from './routes/student/courses'
import { Route as StudentAssessmentsRouteImport } from './routes/student/assessments'
import { Route as CoursesBuilderRouteImport } from './routes/courses/builder'
import { Route as CoursesCourseSlugRouteImport } from './routes/courses/$courseSlug'
import { Route as CategoriesCategorySlugRouteImport } from './routes/categories/$categorySlug'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminCurriculumIndexRouteImport } from './routes/admin/curriculum/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as StudentCourseCourseIdRouteImport } from './routes/student/course/$courseId'
import { Route as StudentAssessmentAssessmentIdRouteImport } from './routes/student/assessment/$assessmentId'
import { Route as AdminCurriculumCourseIdRouteImport } from './routes/admin/curriculum/$courseId'
import { Route as AdminCoursesCourseSlugRouteImport } from './routes/admin/courses/$courseSlug'
import { Route as AdminCategoriesCategoryIdRouteImport } from './routes/admin/categories/$categoryId'
import { Route as AdminAnalyticsPillarsRouteImport } from './routes/admin/analytics/pillars'
import { Route as AdminAnalyticsHoursRouteImport } from './routes/admin/analytics/hours'
import { Route as AdminAnalyticsFlagshipProgramsRouteImport } from './routes/admin/analytics/flagship-programs'
import { Route as AdminAnalyticsExecutiveRouteImport } from './routes/admin/analytics/executive'
import { Route as AdminAnalyticsCoverageRouteImport } from './routes/admin/analytics/coverage'
import { Route as AdminAnalyticsCertificationsRouteImport } from './routes/admin/analytics/certifications'
import { Route as AdminAnalyticsAiTransformationRouteImport } from './routes/admin/analytics/ai-transformation'
import { Route as AdminSubmodulesSubmoduleIdContentRouteImport } from './routes/admin/submodules/$submoduleId/content'

const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganiserRoute = OrganiserRouteImport.update({
  id: '/organiser',
  path: '/organiser',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentResultsRoute = StudentResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFeedbackRoute = StudentFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssessmentsRoute = StudentAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => StudentRoute,
} as any)
const CoursesBuilderRoute = CoursesBuilderRouteImport.update({
  id: '/courses/builder',
  path: '/courses/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSlugRoute = CoursesCourseSlugRouteImport.update({
  id: '/courses/$courseSlug',
  path: '/courses/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategorySlugRoute = CategoriesCategorySlugRouteImport.update({
  id: '/categories/$categorySlug',
  path: '/categories/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCurriculumIndexRoute = AdminCurriculumIndexRouteImport.update({
  id: '/admin/curriculum/',
  path: '/admin/curriculum/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/admin/categories/',
  path: '/admin/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCourseCourseIdRoute = StudentCourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssessmentAssessmentIdRoute =
  StudentAssessmentAssessmentIdRouteImport.update({
    id: '/assessment/$assessmentId',
    path: '/assessment/$assessmentId',
    getParentRoute: () => StudentRoute,
  } as any)
const AdminCurriculumCourseIdRoute = AdminCurriculumCourseIdRouteImport.update({
  id: '/admin/curriculum/$courseId',
  path: '/admin/curriculum/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesCourseSlugRoute = AdminCoursesCourseSlugRouteImport.update({
  id: '/admin/courses/$courseSlug',
  path: '/admin/courses/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesCategoryIdRoute =
  AdminCategoriesCategoryIdRouteImport.update({
    id: '/admin/categories/$categoryId',
    path: '/admin/categories/$categoryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAnalyticsPillarsRoute = AdminAnalyticsPillarsRouteImport.update({
  id: '/pillars',
  path: '/pillars',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsHoursRoute = AdminAnalyticsHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsFlagshipProgramsRoute =
  AdminAnalyticsFlagshipProgramsRouteImport.update({
    id: '/flagship-programs',
    path: '/flagship-programs',
    getParentRoute: () => AdminAnalyticsRoute,
  } as any)
const AdminAnalyticsExecutiveRoute = AdminAnalyticsExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsCoverageRoute = AdminAnalyticsCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsCertificationsRoute =
  AdminAnalyticsCertificationsRouteImport.update({
    id: '/certifications',
    path: '/certifications',
    getParentRoute: () => AdminAnalyticsRoute,
  } as any)
const AdminAnalyticsAiTransformationRoute =
  AdminAnalyticsAiTransformationRouteImport.update({
    id: '/ai-transformation',
    path: '/ai-transformation',
    getParentRoute: () => AdminAnalyticsRoute,
  } as any)
const AdminSubmodulesSubmoduleIdContentRoute =
  AdminSubmodulesSubmoduleIdContentRouteImport.update({
    id: '/admin/submodules/$submoduleId/content',
    path: '/admin/submodules/$submoduleId/content',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/curriculum': typeof CurriculumRoute
  '/organiser': typeof OrganiserRoute
  '/student': typeof StudentRouteWithChildren
  '/trainer': typeof TrainerRoute
  '/admin/analytics': typeof AdminAnalyticsRouteWithChildren
  '/categories/$categorySlug': typeof CategoriesCategorySlugRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/courses/builder': typeof CoursesBuilderRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/feedback': typeof StudentFeedbackRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/results': typeof StudentResultsRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/analytics/ai-transformation': typeof AdminAnalyticsAiTransformationRoute
  '/admin/analytics/certifications': typeof AdminAnalyticsCertificationsRoute
  '/admin/analytics/coverage': typeof AdminAnalyticsCoverageRoute
  '/admin/analytics/executive': typeof AdminAnalyticsExecutiveRoute
  '/admin/analytics/flagship-programs': typeof AdminAnalyticsFlagshipProgramsRoute
  '/admin/analytics/hours': typeof AdminAnalyticsHoursRoute
  '/admin/analytics/pillars': typeof AdminAnalyticsPillarsRoute
  '/admin/categories/$categoryId': typeof AdminCategoriesCategoryIdRoute
  '/admin/courses/$courseSlug': typeof AdminCoursesCourseSlugRoute
  '/admin/curriculum/$courseId': typeof AdminCurriculumCourseIdRoute
  '/student/assessment/$assessmentId': typeof StudentAssessmentAssessmentIdRoute
  '/student/course/$courseId': typeof StudentCourseCourseIdRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/curriculum/': typeof AdminCurriculumIndexRoute
  '/admin/submodules/$submoduleId/content': typeof AdminSubmodulesSubmoduleIdContentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/curriculum': typeof CurriculumRoute
  '/organiser': typeof OrganiserRoute
  '/trainer': typeof TrainerRoute
  '/admin/analytics': typeof AdminAnalyticsRouteWithChildren
  '/categories/$categorySlug': typeof CategoriesCategorySlugRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/courses/builder': typeof CoursesBuilderRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/feedback': typeof StudentFeedbackRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/results': typeof StudentResultsRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/analytics/ai-transformation': typeof AdminAnalyticsAiTransformationRoute
  '/admin/analytics/certifications': typeof AdminAnalyticsCertificationsRoute
  '/admin/analytics/coverage': typeof AdminAnalyticsCoverageRoute
  '/admin/analytics/executive': typeof AdminAnalyticsExecutiveRoute
  '/admin/analytics/flagship-programs': typeof AdminAnalyticsFlagshipProgramsRoute
  '/admin/analytics/hours': typeof AdminAnalyticsHoursRoute
  '/admin/analytics/pillars': typeof AdminAnalyticsPillarsRoute
  '/admin/categories/$categoryId': typeof AdminCategoriesCategoryIdRoute
  '/admin/courses/$courseSlug': typeof AdminCoursesCourseSlugRoute
  '/admin/curriculum/$courseId': typeof AdminCurriculumCourseIdRoute
  '/student/assessment/$assessmentId': typeof StudentAssessmentAssessmentIdRoute
  '/student/course/$courseId': typeof StudentCourseCourseIdRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/curriculum': typeof AdminCurriculumIndexRoute
  '/admin/submodules/$submoduleId/content': typeof AdminSubmodulesSubmoduleIdContentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/curriculum': typeof CurriculumRoute
  '/organiser': typeof OrganiserRoute
  '/student': typeof StudentRouteWithChildren
  '/trainer': typeof TrainerRoute
  '/admin/analytics': typeof AdminAnalyticsRouteWithChildren
  '/categories/$categorySlug': typeof CategoriesCategorySlugRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/courses/builder': typeof CoursesBuilderRoute
  '/student/assessments': typeof StudentAssessmentsRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/feedback': typeof StudentFeedbackRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/results': typeof StudentResultsRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/analytics/ai-transformation': typeof AdminAnalyticsAiTransformationRoute
  '/admin/analytics/certifications': typeof AdminAnalyticsCertificationsRoute
  '/admin/analytics/coverage': typeof AdminAnalyticsCoverageRoute
  '/admin/analytics/executive': typeof AdminAnalyticsExecutiveRoute
  '/admin/analytics/flagship-programs': typeof AdminAnalyticsFlagshipProgramsRoute
  '/admin/analytics/hours': typeof AdminAnalyticsHoursRoute
  '/admin/analytics/pillars': typeof AdminAnalyticsPillarsRoute
  '/admin/categories/$categoryId': typeof AdminCategoriesCategoryIdRoute
  '/admin/courses/$courseSlug': typeof AdminCoursesCourseSlugRoute
  '/admin/curriculum/$courseId': typeof AdminCurriculumCourseIdRoute
  '/student/assessment/$assessmentId': typeof StudentAssessmentAssessmentIdRoute
  '/student/course/$courseId': typeof StudentCourseCourseIdRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/curriculum/': typeof AdminCurriculumIndexRoute
  '/admin/submodules/$submoduleId/content': typeof AdminSubmodulesSubmoduleIdContentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/curriculum'
    | '/organiser'
    | '/student'
    | '/trainer'
    | '/admin/analytics'
    | '/categories/$categorySlug'
    | '/courses/$courseSlug'
    | '/courses/builder'
    | '/student/assessments'
    | '/student/courses'
    | '/student/feedback'
    | '/student/notifications'
    | '/student/profile'
    | '/student/results'
    | '/analytics/'
    | '/categories/'
    | '/courses/'
    | '/student/'
    | '/admin/analytics/ai-transformation'
    | '/admin/analytics/certifications'
    | '/admin/analytics/coverage'
    | '/admin/analytics/executive'
    | '/admin/analytics/flagship-programs'
    | '/admin/analytics/hours'
    | '/admin/analytics/pillars'
    | '/admin/categories/$categoryId'
    | '/admin/courses/$courseSlug'
    | '/admin/curriculum/$courseId'
    | '/student/assessment/$assessmentId'
    | '/student/course/$courseId'
    | '/admin/categories/'
    | '/admin/curriculum/'
    | '/admin/submodules/$submoduleId/content'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/curriculum'
    | '/organiser'
    | '/trainer'
    | '/admin/analytics'
    | '/categories/$categorySlug'
    | '/courses/$courseSlug'
    | '/courses/builder'
    | '/student/assessments'
    | '/student/courses'
    | '/student/feedback'
    | '/student/notifications'
    | '/student/profile'
    | '/student/results'
    | '/analytics'
    | '/categories'
    | '/courses'
    | '/student'
    | '/admin/analytics/ai-transformation'
    | '/admin/analytics/certifications'
    | '/admin/analytics/coverage'
    | '/admin/analytics/executive'
    | '/admin/analytics/flagship-programs'
    | '/admin/analytics/hours'
    | '/admin/analytics/pillars'
    | '/admin/categories/$categoryId'
    | '/admin/courses/$courseSlug'
    | '/admin/curriculum/$courseId'
    | '/student/assessment/$assessmentId'
    | '/student/course/$courseId'
    | '/admin/categories'
    | '/admin/curriculum'
    | '/admin/submodules/$submoduleId/content'
  id:
    | '__root__'
    | '/'
    | '/curriculum'
    | '/organiser'
    | '/student'
    | '/trainer'
    | '/admin/analytics'
    | '/categories/$categorySlug'
    | '/courses/$courseSlug'
    | '/courses/builder'
    | '/student/assessments'
    | '/student/courses'
    | '/student/feedback'
    | '/student/notifications'
    | '/student/profile'
    | '/student/results'
    | '/analytics/'
    | '/categories/'
    | '/courses/'
    | '/student/'
    | '/admin/analytics/ai-transformation'
    | '/admin/analytics/certifications'
    | '/admin/analytics/coverage'
    | '/admin/analytics/executive'
    | '/admin/analytics/flagship-programs'
    | '/admin/analytics/hours'
    | '/admin/analytics/pillars'
    | '/admin/categories/$categoryId'
    | '/admin/courses/$courseSlug'
    | '/admin/curriculum/$courseId'
    | '/student/assessment/$assessmentId'
    | '/student/course/$courseId'
    | '/admin/categories/'
    | '/admin/curriculum/'
    | '/admin/submodules/$submoduleId/content'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CurriculumRoute: typeof CurriculumRoute
  OrganiserRoute: typeof OrganiserRoute
  StudentRoute: typeof StudentRouteWithChildren
  TrainerRoute: typeof TrainerRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRouteWithChildren
  CategoriesCategorySlugRoute: typeof CategoriesCategorySlugRoute
  CoursesCourseSlugRoute: typeof CoursesCourseSlugRoute
  CoursesBuilderRoute: typeof CoursesBuilderRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  AdminCategoriesCategoryIdRoute: typeof AdminCategoriesCategoryIdRoute
  AdminCoursesCourseSlugRoute: typeof AdminCoursesCourseSlugRoute
  AdminCurriculumCourseIdRoute: typeof AdminCurriculumCourseIdRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminCurriculumIndexRoute: typeof AdminCurriculumIndexRoute
  AdminSubmodulesSubmoduleIdContentRoute: typeof AdminSubmodulesSubmoduleIdContentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organiser': {
      id: '/organiser'
      path: '/organiser'
      fullPath: '/organiser'
      preLoaderRoute: typeof OrganiserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/results': {
      id: '/student/results'
      path: '/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof StudentResultsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/feedback': {
      id: '/student/feedback'
      path: '/feedback'
      fullPath: '/student/feedback'
      preLoaderRoute: typeof StudentFeedbackRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assessments': {
      id: '/student/assessments'
      path: '/assessments'
      fullPath: '/student/assessments'
      preLoaderRoute: typeof StudentAssessmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/courses/builder': {
      id: '/courses/builder'
      path: '/courses/builder'
      fullPath: '/courses/builder'
      preLoaderRoute: typeof CoursesBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug': {
      id: '/courses/$courseSlug'
      path: '/courses/$courseSlug'
      fullPath: '/courses/$courseSlug'
      preLoaderRoute: typeof CoursesCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categorySlug': {
      id: '/categories/$categorySlug'
      path: '/categories/$categorySlug'
      fullPath: '/categories/$categorySlug'
      preLoaderRoute: typeof CategoriesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/curriculum/': {
      id: '/admin/curriculum/'
      path: '/admin/curriculum'
      fullPath: '/admin/curriculum/'
      preLoaderRoute: typeof AdminCurriculumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/admin/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/course/$courseId': {
      id: '/student/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/student/course/$courseId'
      preLoaderRoute: typeof StudentCourseCourseIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assessment/$assessmentId': {
      id: '/student/assessment/$assessmentId'
      path: '/assessment/$assessmentId'
      fullPath: '/student/assessment/$assessmentId'
      preLoaderRoute: typeof StudentAssessmentAssessmentIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/curriculum/$courseId': {
      id: '/admin/curriculum/$courseId'
      path: '/admin/curriculum/$courseId'
      fullPath: '/admin/curriculum/$courseId'
      preLoaderRoute: typeof AdminCurriculumCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/$courseSlug': {
      id: '/admin/courses/$courseSlug'
      path: '/admin/courses/$courseSlug'
      fullPath: '/admin/courses/$courseSlug'
      preLoaderRoute: typeof AdminCoursesCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories/$categoryId': {
      id: '/admin/categories/$categoryId'
      path: '/admin/categories/$categoryId'
      fullPath: '/admin/categories/$categoryId'
      preLoaderRoute: typeof AdminCategoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics/pillars': {
      id: '/admin/analytics/pillars'
      path: '/pillars'
      fullPath: '/admin/analytics/pillars'
      preLoaderRoute: typeof AdminAnalyticsPillarsRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/admin/analytics/hours': {
      id: '/admin/analytics/hours'
      path: '/hours'
      fullPath: '/admin/analytics/hours'
      preLoaderRoute: typeof AdminAnalyticsHoursRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/admin/analytics/flagship-programs': {
      id: '/admin/analytics/flagship-programs'
      path: '/flagship-programs'
      fullPath: '/admin/analytics/flagship-programs'
      preLoaderRoute: typeof AdminAnalyticsFlagshipProgramsRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/admin/analytics/executive': {
      id: '/admin/analytics/executive'
      path: '/executive'
      fullPath: '/admin/analytics/executive'
      preLoaderRoute: typeof AdminAnalyticsExecutiveRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/admin/analytics/coverage': {
      id: '/admin/analytics/coverage'
      path: '/coverage'
      fullPath: '/admin/analytics/coverage'
      preLoaderRoute: typeof AdminAnalyticsCoverageRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/admin/analytics/certifications': {
      id: '/admin/analytics/certifications'
      path: '/certifications'
      fullPath: '/admin/analytics/certifications'
      preLoaderRoute: typeof AdminAnalyticsCertificationsRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/admin/analytics/ai-transformation': {
      id: '/admin/analytics/ai-transformation'
      path: '/ai-transformation'
      fullPath: '/admin/analytics/ai-transformation'
      preLoaderRoute: typeof AdminAnalyticsAiTransformationRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/admin/submodules/$submoduleId/content': {
      id: '/admin/submodules/$submoduleId/content'
      path: '/admin/submodules/$submoduleId/content'
      fullPath: '/admin/submodules/$submoduleId/content'
      preLoaderRoute: typeof AdminSubmodulesSubmoduleIdContentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudentRouteChildren {
  StudentAssessmentsRoute: typeof StudentAssessmentsRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentFeedbackRoute: typeof StudentFeedbackRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentResultsRoute: typeof StudentResultsRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentAssessmentAssessmentIdRoute: typeof StudentAssessmentAssessmentIdRoute
  StudentCourseCourseIdRoute: typeof StudentCourseCourseIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAssessmentsRoute: StudentAssessmentsRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentFeedbackRoute: StudentFeedbackRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentResultsRoute: StudentResultsRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentAssessmentAssessmentIdRoute: StudentAssessmentAssessmentIdRoute,
  StudentCourseCourseIdRoute: StudentCourseCourseIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface AdminAnalyticsRouteChildren {
  AdminAnalyticsAiTransformationRoute: typeof AdminAnalyticsAiTransformationRoute
  AdminAnalyticsCertificationsRoute: typeof AdminAnalyticsCertificationsRoute
  AdminAnalyticsCoverageRoute: typeof AdminAnalyticsCoverageRoute
  AdminAnalyticsExecutiveRoute: typeof AdminAnalyticsExecutiveRoute
  AdminAnalyticsFlagshipProgramsRoute: typeof AdminAnalyticsFlagshipProgramsRoute
  AdminAnalyticsHoursRoute: typeof AdminAnalyticsHoursRoute
  AdminAnalyticsPillarsRoute: typeof AdminAnalyticsPillarsRoute
}

const AdminAnalyticsRouteChildren: AdminAnalyticsRouteChildren = {
  AdminAnalyticsAiTransformationRoute: AdminAnalyticsAiTransformationRoute,
  AdminAnalyticsCertificationsRoute: AdminAnalyticsCertificationsRoute,
  AdminAnalyticsCoverageRoute: AdminAnalyticsCoverageRoute,
  AdminAnalyticsExecutiveRoute: AdminAnalyticsExecutiveRoute,
  AdminAnalyticsFlagshipProgramsRoute: AdminAnalyticsFlagshipProgramsRoute,
  AdminAnalyticsHoursRoute: AdminAnalyticsHoursRoute,
  AdminAnalyticsPillarsRoute: AdminAnalyticsPillarsRoute,
}

const AdminAnalyticsRouteWithChildren = AdminAnalyticsRoute._addFileChildren(
  AdminAnalyticsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CurriculumRoute: CurriculumRoute,
  OrganiserRoute: OrganiserRoute,
  StudentRoute: StudentRouteWithChildren,
  TrainerRoute: TrainerRoute,
  AdminAnalyticsRoute: AdminAnalyticsRouteWithChildren,
  CategoriesCategorySlugRoute: CategoriesCategorySlugRoute,
  CoursesCourseSlugRoute: CoursesCourseSlugRoute,
  CoursesBuilderRoute: CoursesBuilderRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  AdminCategoriesCategoryIdRoute: AdminCategoriesCategoryIdRoute,
  AdminCoursesCourseSlugRoute: AdminCoursesCourseSlugRoute,
  AdminCurriculumCourseIdRoute: AdminCurriculumCourseIdRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminCurriculumIndexRoute: AdminCurriculumIndexRoute,
  AdminSubmodulesSubmoduleIdContentRoute:
    AdminSubmodulesSubmoduleIdContentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.js'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
