/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as ManagerRouteRouteImport } from './routes/manager/route';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ManagerIndexRouteImport } from './routes/manager/index';
import { Route as ManagerUsersRouteImport } from './routes/manager/users';
import { Route as ManagerFeedbackRouteImport } from './routes/manager/feedback';
import { Route as ManagerApprovalsRouteImport } from './routes/manager/approvals';
import { Route as ManagerAnalyticsRouteImport } from './routes/manager/analytics';

const ManagerRouteRoute = ManagerRouteRouteImport.update({
    id: '/manager',
    path: '/manager',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const ManagerIndexRoute = ManagerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ManagerRouteRoute,
});
const ManagerUsersRoute = ManagerUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ManagerRouteRoute,
});
const ManagerFeedbackRoute = ManagerFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => ManagerRouteRoute,
});
const ManagerApprovalsRoute = ManagerApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => ManagerRouteRoute,
});
const ManagerAnalyticsRoute = ManagerAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => ManagerRouteRoute,
});

const ManagerRouteRouteChildren = {
    ManagerAnalyticsRoute: ManagerAnalyticsRoute,
    ManagerApprovalsRoute: ManagerApprovalsRoute,
    ManagerFeedbackRoute: ManagerFeedbackRoute,
    ManagerUsersRoute: ManagerUsersRoute,
    ManagerIndexRoute: ManagerIndexRoute,
};

const ManagerRouteRouteWithChildren = ManagerRouteRoute._addFileChildren(
    ManagerRouteRouteChildren,
);

const rootRouteChildren = {
    IndexRoute: IndexRoute,
    ManagerRouteRoute: ManagerRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
