ALTER TABLE course.courses 
ADD COLUMN IF NOT EXISTS course_code VARCHAR(255),
ADD COLUMN IF NOT EXISTS icon VARCHAR(255),
ADD COLUMN IF NOT EXISTS banner_image VARCHAR(255),
ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS allow_enrolling BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS highlights TEXT[],
ADD COLUMN IF NOT EXISTS career_opportunities TEXT[];
