ALTER TABLE course.courses 
ADD COLUMN is_active BOOLEAN DEFAULT true,
ADD COLUMN is_featured BOOLEAN DEFAULT false,
ADD COLUMN allow_indexing BOOLEAN DEFAULT true,
ADD COLUMN show_in_search BOOLEAN DEFAULT true,
ADD COLUMN og_title VARCHAR(255),
ADD COLUMN og_description TEXT,
ADD COLUMN og_image TEXT,
ADD COLUMN og_url TEXT,
ADD COLUMN og_type VARCHAR(100) DEFAULT 'website',
ADD COLUMN twitter_title VARCHAR(255),
ADD COLUMN twitter_description TEXT,
ADD COLUMN twitter_image TEXT,
ADD COLUMN twitter_card VARCHAR(100) DEFAULT 'summary_large_image',
ADD COLUMN search_intent TEXT,
ADD COLUMN semantic_keywords TEXT,
ADD COLUMN related_topics TEXT,
ADD COLUMN search_synonyms TEXT,
ADD COLUMN faq_content TEXT,
ADD COLUMN custom_head_script TEXT,
ADD COLUMN custom_body_script TEXT;
