ALTER TABLE course.courses 
ADD COLUMN IF NOT EXISTS meta_keywords TEXT,
ADD COLUMN IF NOT EXISTS schema_markup TEXT,
ADD COLUMN IF NOT EXISTS faq_schema TEXT,
ADD COLUMN IF NOT EXISTS breadcrumb_schema TEXT,
ADD COLUMN IF NOT EXISTS preview_video_url TEXT,
ADD COLUMN IF NOT EXISTS total_views BIGINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_clicks BIGINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS ctr DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS seo_score INTEGER DEFAULT 0;
